name: flutbeat
description: TrackPlayer with Flutter

version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.35
  file_picker: ^6.0.0
  permission_handler: ^11.0.1
  external_path: ^1.0.3
  audio_service: ^0.18.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  generate: true
  # assets:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
