name: flutplayer
description: Player with Flutter

version: 2.0.0

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  path: any
  flutter:
    sdk: flutter
  flutter_soloud: ^4.0.4
  file_picker: ^11.0.2
  permission_handler: ^12.0.1
  audio_service: ^0.18.12
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.4.0+3
  shared_preferences: ^2.5.5
  media_kit: ^1.1.11
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.4
  video_player: ^2.8.2
  win32: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/NoCopyrightSounds_logo.png
